// src/app/terms/page.js
'use client'

import { useRouter } from 'next/navigation'
import { ArrowLeft, Car } from 'lucide-react'

const EFFECTIVE_DATE = '1 June 2025'

export default function TermsPage() {
  const router = useRouter()

  return (
    <div className="min-h-screen bg-gray-50">
      {/* Header */}
      <div className="bg-white border-b border-gray-200 sticky top-0 z-10">
        <div className="max-w-3xl mx-auto px-4 py-3 flex items-center gap-3">
          <button onClick={() => router.back()}
            className="p-1.5 rounded-lg text-gray-400 hover:text-gray-700 hover:bg-gray-100">
            <ArrowLeft size={18} />
          </button>
          <div className="flex items-center gap-2">
            <Car size={18} className="text-blue-600" />
            <span className="font-bold text-gray-900 text-sm">Carfix-Connect</span>
          </div>
        </div>
      </div>

      {/* Content */}
      <div className="max-w-3xl mx-auto px-4 py-10">
        <h1 className="text-3xl font-bold text-gray-900 mb-2">Terms and Conditions</h1>
        <p className="text-sm text-gray-500 mb-8">Effective Date: {EFFECTIVE_DATE}</p>

        <div className="prose prose-sm prose-gray max-w-none
          [&_h2]:text-lg [&_h2]:font-bold [&_h2]:text-gray-900 [&_h2]:mt-8 [&_h2]:mb-3
          [&_h3]:text-base [&_h3]:font-semibold [&_h3]:text-gray-800 [&_h3]:mt-5 [&_h3]:mb-2
          [&_p]:text-gray-700 [&_p]:leading-relaxed [&_p]:mb-3
          [&_ul]:text-gray-700 [&_ul]:mb-3 [&_ul]:ml-4
          [&_li]:mb-1.5
          [&_strong]:text-gray-900
        ">

          <p>
            Welcome to Carfix-Connect. These Terms and Conditions (&quot;Terms&quot;) constitute a legally
            binding agreement between you and Carfix-Connect (&quot;we&quot;, &quot;us&quot;, &quot;our&quot;,
            or &quot;the Platform&quot;) governing your access to and use of the Carfix-Connect website,
            mobile application, and all related services (collectively, the &quot;Services&quot;).
          </p>
          <p>
            By creating an account, accessing, or using our Services, you acknowledge that you have
            read, understood, and agree to be bound by these Terms. If you do not agree to these
            Terms, do not use the Services.
          </p>

          <h2>1. Definitions</h2>
          <ul>
            <li><strong>&quot;User&quot;</strong> means any individual who creates an account on the Platform, including vehicle owners, company employees, and service provider staff.</li>
            <li><strong>&quot;Vehicle Owner&quot;</strong> means an individual who registers personal vehicles on the Platform for maintenance tracking and service bookings.</li>
            <li><strong>&quot;Company&quot;</strong> means a business entity that registers on the Platform to manage a fleet of vehicles, including its owner, administrators, and team members.</li>
            <li><strong>&quot;Service Provider&quot;</strong> means a business (garage, workshop, car wash, tyre shop, or similar) that registers on the Platform to offer vehicle maintenance and repair services.</li>
            <li><strong>&quot;Shop&quot;</strong> means a physical location registered by a Service Provider where services are performed.</li>
            <li><strong>&quot;Booking&quot;</strong> means a service appointment created by a User or Company through the Platform.</li>
            <li><strong>&quot;Work Order&quot;</strong> means a detailed record of services, labour, and parts associated with a Booking, created by the Service Provider.</li>
            <li><strong>&quot;Invoice&quot;</strong> means a payment request generated by a Service Provider for completed work.</li>
            <li><strong>&quot;Verification&quot;</strong> means the process by which Carfix-Connect reviews and validates the credentials of Service Providers and Companies.</li>
          </ul>

          <h2>2. Eligibility</h2>
          <p>
            You must be at least 18 years of age and legally capable of entering into binding
            contracts under the laws of your jurisdiction to use the Services. By registering, you
            represent and warrant that you meet these requirements. If you are registering on behalf
            of a Company or Service Provider, you represent that you have the authority to bind that
            entity to these Terms.
          </p>

          <h2>3. Account Registration</h2>
          <h3>3.1 Account Creation</h3>
          <p>
            To access the Services, you must create an account by providing accurate and complete
            information including your name, email address, phone number, and any other information
            requested during registration. You are responsible for maintaining the confidentiality
            of your account credentials.
          </p>
          <h3>3.2 Account Types</h3>
          <p>
            The Platform supports multiple account types: individual vehicle owners, company fleet
            managers, service provider owners, and their respective team members. Each account type
            has different features and permissions as determined by the Platform.
          </p>
          <h3>3.3 Account Security</h3>
          <p>
            You are solely responsible for all activities that occur under your account. You must
            immediately notify Carfix-Connect of any unauthorised use of your account or any other
            security breach. Carfix-Connect shall not be liable for any loss arising from your failure
            to safeguard your account credentials.
          </p>

          <h2>4. Service Provider Terms</h2>
          <h3>4.1 Registration and Verification</h3>
          <p>
            Service Providers must complete a registration process that includes providing business
            registration documents, tax compliance certificates, identification documents, and other
            credentials as required by Carfix-Connect and applicable local regulations. Carfix-Connect reserves
            the right to verify, approve, reject, or suspend any Service Provider registration at
            its sole discretion.
          </p>
          <h3>4.2 Verification Score</h3>
          <p>
            Each Service Provider receives a verification score based on the completeness and
            validity of their documentation, business registration status, tax compliance, physical
            location verification, and profile completeness. This score is displayed publicly to
            help Users make informed choices. Carfix-Connect does not guarantee the accuracy or reliability
            of any Service Provider beyond the scope of the verification process.
          </p>
          <h3>4.3 Service Provider Obligations</h3>
          <p>Service Providers agree to:</p>
          <ul>
            <li>Provide accurate and up-to-date information about their business, services, pricing, and operating hours.</li>
            <li>Maintain valid business licences, insurance, and regulatory compliance as required by applicable laws in your jurisdiction.</li>
            <li>Deliver services with reasonable skill, care, and in accordance with industry standards.</li>
            <li>Honour bookings made through the Platform and communicate promptly regarding any changes or cancellations.</li>
            <li>Maintain accurate records of all work performed, parts used, and charges applied.</li>
            <li>Not engage in deceptive, fraudulent, or misleading practices.</li>
          </ul>
          <h3>4.4 Listing and Pricing</h3>
          <p>
            Service Providers are solely responsible for setting their own prices. Carfix-Connect does not
            set, regulate, or guarantee pricing. All prices displayed on the Platform are set by the
            respective Service Provider and may be subject to change.
          </p>

          <h2>5. Company and Fleet Management Terms</h2>
          <h3>5.1 Company Registration</h3>
          <p>
            Companies must complete a registration and verification process similar to Service
            Providers, including provision of certificates of incorporation, tax compliance
            documentation, and director identification. The company owner is responsible for all
            activities conducted under the company account, including those of invited team members.
          </p>
          <h3>5.2 Team Members</h3>
          <p>
            Company owners may invite team members to join the company account. By inviting a team
            member, the company owner authorises that individual to act on behalf of the company
            within the permissions granted. The company owner is responsible for managing team member
            access and permissions.
          </p>
          <h3>5.3 Vehicle Registration</h3>
          <p>
            Companies and individual Users may register vehicles on the Platform. By registering a
            vehicle, you represent that you are the owner or authorised manager of that vehicle.
            Carfix-Connect is not responsible for verifying vehicle ownership beyond the information provided.
          </p>

          <h2>6. Bookings and Work Orders</h2>
          <h3>6.1 Booking Process</h3>
          <p>
            Users may create bookings with verified Service Providers through the Platform. A booking
            constitutes a request for services and is subject to confirmation by the Service Provider.
            Carfix-Connect facilitates the booking process but is not a party to the service agreement
            between the User and the Service Provider.
          </p>
          <h3>6.2 Cancellations</h3>
          <p>
            Cancellation policies are determined by individual Service Providers. Users should review
            the applicable cancellation policy before confirming a booking. Carfix-Connect is not responsible
            for any charges, penalties, or disputes arising from cancellations.
          </p>
          <h3>6.3 Work Orders and Invoicing</h3>
          <p>
            Service Providers create work orders to document services performed. Invoices generated
            through the Platform are between the User/Company and the Service Provider. Carfix-Connect
            does not process payments directly and is not responsible for payment disputes between
            Users and Service Providers.
          </p>

          <h2>7. Payments</h2>
          <p>
            All financial transactions arising from services booked through the Platform are
            between the User/Company and the Service Provider. Carfix-Connect may facilitate payment
            processing through integrated third-party payment providers in the future. Users and
            Service Providers are responsible for their own tax obligations. Carfix-Connect does not
            collect, hold, or disburse funds on behalf of any party unless explicitly stated.
          </p>

          <h2>8. User Conduct</h2>
          <p>You agree not to:</p>
          <ul>
            <li>Use the Services for any unlawful purpose or in violation of any applicable law or regulation.</li>
            <li>Provide false, inaccurate, or misleading information.</li>
            <li>Impersonate any person or entity, or misrepresent your affiliation with any person or entity.</li>
            <li>Interfere with or disrupt the Services, servers, or networks connected to the Services.</li>
            <li>Attempt to gain unauthorised access to any part of the Services, other accounts, or computer systems.</li>
            <li>Use automated scripts, bots, or scrapers to access or collect data from the Platform.</li>
            <li>Engage in harassment, abuse, or intimidation of other Users or Service Providers.</li>
            <li>Post reviews or feedback that are false, defamatory, or intended to manipulate ratings.</li>
            <li>Use the Platform to solicit Users or Service Providers for transactions outside the Platform.</li>
          </ul>

          <h2>9. Reviews and Ratings</h2>
          <p>
            Users may submit reviews and ratings for Service Providers. Reviews must be honest,
            accurate, and based on genuine experiences. Carfix-Connect reserves the right to remove reviews
            that violate these Terms or are deemed fraudulent, abusive, or inappropriate. Service
            Providers may respond to reviews through the Platform. Carfix-Connect does not endorse or
            verify the accuracy of user reviews.
          </p>

          <h2>10. Intellectual Property</h2>
          <h3>10.1 Platform Content</h3>
          <p>
            All content, features, and functionality of the Platform — including but not limited to
            text, graphics, logos, icons, images, software, and the overall look and feel — are owned
            by Carfix-Connect or its licensors and are protected by applicable intellectual
            property laws. You may not reproduce, distribute, modify, or create derivative works
            without prior written consent.
          </p>
          <h3>10.2 User Content</h3>
          <p>
            By submitting content to the Platform (reviews, images, documents, descriptions), you
            grant Carfix-Connect a non-exclusive, royalty-free, worldwide licence to use, display, and
            distribute such content in connection with the Services. You retain ownership of your
            content and are solely responsible for its accuracy and legality.
          </p>

          <h2>11. Data Protection and Privacy</h2>
          <p>
            Your privacy is important to us. Our collection, use, and protection of personal data
            is governed by our Privacy Policy, which forms part of these Terms. By using the Services,
            you consent to the collection and processing of your data as described in the Privacy Policy.
          </p>
          <p>We comply with applicable data protection laws in the jurisdictions where we operate, and we:</p>
          <ul>
            <li>Collect only the data necessary to provide the Services.</li>
            <li>Store data securely using industry-standard encryption and access controls.</li>
            <li>Do not sell personal data to third parties.</li>
            <li>Provide mechanisms for you to access, correct, or delete your personal data.</li>
            <li>Retain data only as long as necessary for the purposes for which it was collected or as required by law.</li>
          </ul>

          <h2>12. Account Suspension and Termination</h2>
          <h3>12.1 By Carfix-Connect</h3>
          <p>
            Carfix-Connect reserves the right to suspend, deactivate, or terminate any account at any time,
            with or without notice, for any reason, including but not limited to:
          </p>
          <ul>
            <li>Violation of these Terms or any applicable laws.</li>
            <li>Fraudulent, abusive, or harmful conduct.</li>
            <li>Failure to maintain valid documentation or regulatory compliance (for Service Providers and Companies).</li>
            <li>Prolonged inactivity.</li>
            <li>At the request of law enforcement or regulatory authorities.</li>
          </ul>
          <h3>12.2 By You</h3>
          <p>
            You may deactivate your account at any time by contacting support. Deactivation does not
            erase your data immediately — data retention is governed by our Privacy Policy and applicable
            law. Outstanding obligations (unpaid invoices, pending bookings) must be resolved before
            account closure.
          </p>
          <h3>12.3 Effect of Termination</h3>
          <p>
            Upon termination, your right to access the Services ceases immediately. Carfix-Connect may retain
            certain data as required by law or legitimate business purposes. Provisions that by their
            nature should survive termination (including intellectual property, limitation of liability,
            and dispute resolution) shall survive.
          </p>

          <h2>13. Disclaimers</h2>
          <h3>13.1 Platform Role</h3>
          <p>
            Carfix-Connect is a technology platform that connects vehicle owners and companies with service
            providers. <strong>Carfix-Connect is not a garage, workshop, or service provider.</strong> We do
            not perform, supervise, or guarantee any vehicle maintenance or repair services. All services
            are provided by independent third-party Service Providers.
          </p>
          <h3>13.2 No Warranty</h3>
          <p>
            The Services are provided &quot;as is&quot; and &quot;as available&quot; without warranties
            of any kind, whether express or implied, including but not limited to implied warranties of
            merchantability, fitness for a particular purpose, and non-infringement. Carfix-Connect does not
            warrant that the Services will be uninterrupted, error-free, or secure.
          </p>
          <h3>13.3 Service Quality</h3>
          <p>
            Carfix-Connect does not guarantee the quality, safety, legality, or suitability of any services
            provided by Service Providers. While we conduct verification checks, these do not constitute
            endorsement or certification. Users engage Service Providers at their own risk and should
            exercise their own judgment.
          </p>

          <h2>14. Limitation of Liability</h2>
          <p>
            To the maximum extent permitted by law, Carfix-Connect, its directors, employees, agents, and
            affiliates shall not be liable for:
          </p>
          <ul>
            <li>Any indirect, incidental, special, consequential, or punitive damages.</li>
            <li>Any loss of profits, revenue, data, or business opportunities.</li>
            <li>Any damages arising from the services provided by Service Providers.</li>
            <li>Any damages resulting from unauthorised access to or alteration of your account or data.</li>
            <li>Any damages exceeding the total fees paid by you to Carfix-Connect (if any) in the twelve months preceding the claim.</li>
          </ul>

          <h2>15. Indemnification</h2>
          <p>
            You agree to indemnify, defend, and hold harmless Carfix-Connect and its officers, directors,
            employees, and agents from and against any claims, damages, losses, liabilities, costs,
            and expenses (including legal fees) arising out of or related to your use of the Services,
            your violation of these Terms, or your violation of any rights of a third party.
          </p>

          <h2>16. Dispute Resolution</h2>
          <h3>16.1 Between Users and Service Providers</h3>
          <p>
            Disputes between Users/Companies and Service Providers regarding services, pricing, quality,
            or any other matter are between those parties. Carfix-Connect may, at its sole discretion, offer
            mediation assistance but is not obligated to resolve such disputes.
          </p>
          <h3>16.2 Between You and Carfix-Connect</h3>
          <p>
            Any dispute arising out of or relating to these Terms or the Services shall first be
            attempted to be resolved through good-faith negotiation. If the dispute cannot be resolved
            within thirty (30) days, either party may submit the dispute to mediation or arbitration
            in accordance with the applicable arbitration laws in the jurisdiction where Carfix-Connect is
            incorporated. The seat of arbitration shall be determined by Carfix-Connect&apos;s registered
            office location at the time the dispute arises.
          </p>

          <h2>17. Governing Law</h2>
          <p>
            These Terms shall be governed by and construed in accordance with the laws of the
            jurisdiction where Carfix-Connect is incorporated. Any legal proceedings arising out of
            these Terms shall be subject to the exclusive jurisdiction of the courts in that
            jurisdiction, without prejudice to the arbitration clause above. As Carfix-Connect expands
            to additional regions, supplementary regional terms may apply and will be communicated
            to affected Users.
          </p>

          <h2>18. Notifications</h2>
          <p>
            Carfix-Connect may send you notifications regarding your account, bookings, service updates,
            and promotional offers via email, SMS, push notifications, or in-app messages. You may
            opt out of promotional communications at any time through your account settings.
            Transactional notifications (booking confirmations, account alerts, security notices)
            cannot be opted out of while your account is active.
          </p>

          <h2>19. Modifications to Terms</h2>
          <p>
            Carfix-Connect reserves the right to modify these Terms at any time. We will notify you of
            material changes by posting the updated Terms on the Platform and, where practicable,
            by sending you a notification. Your continued use of the Services after the effective
            date of any modification constitutes your acceptance of the modified Terms. If you do
            not agree with the modified Terms, you must stop using the Services and deactivate
            your account.
          </p>

          <h2>20. General Provisions</h2>
          <ul>
            <li><strong>Entire Agreement:</strong> These Terms, together with the Privacy Policy, constitute the entire agreement between you and Carfix-Connect regarding the Services.</li>
            <li><strong>Severability:</strong> If any provision of these Terms is held to be invalid or unenforceable, the remaining provisions shall continue in full force and effect.</li>
            <li><strong>Waiver:</strong> The failure of Carfix-Connect to enforce any right or provision of these Terms shall not constitute a waiver of that right or provision.</li>
            <li><strong>Assignment:</strong> You may not assign or transfer these Terms without Carfix-Connect&apos;s prior written consent. Carfix-Connect may assign these Terms without restriction.</li>
            <li><strong>Force Majeure:</strong> Carfix-Connect shall not be liable for any delay or failure to perform resulting from causes beyond its reasonable control, including natural disasters, war, strikes, government actions, or infrastructure failures.</li>
          </ul>

          <h2>21. Contact Information</h2>
          <p>
            If you have questions, concerns, or feedback about these Terms, please contact us:
          </p>
          <ul>
            <li><strong>Email:</strong> legal@carfix-connect.com</li>
            <li><strong>Support:</strong> support@carfix-connect.com</li>
            <li><strong>Address:</strong> See our website for current office locations.</li>
          </ul>

          <div className="mt-10 pt-6 border-t border-gray-200">
            <p className="text-xs text-gray-400 italic">
              Last updated: {EFFECTIVE_DATE}. Previous versions of these Terms are available upon request.
            </p>
          </div>
        </div>
      </div>
    </div>
  )
}